#Oracle配置
#spring:
#  datasource:
#    driverClassName: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@127.0.0.1:1521:ORCLCDB
#    username: GUNS
#    password: GUNS
#    filters: wall,mergeStat

#SQLServer配置
#spring:
#  datasource:
#    driverClassName: net.sourceforge.jtds.jdbc.Driver
#    url: jdbc:jtds:sqlserver://127.0.0.1:3433;DatabaseName=guns
#    username: guns
#    password: 123456
#    filters: wall,mergeStat

#PostgreSQL配置
#spring:
#  datasource:
#    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://127.0.0.1:5432/guns
#    username: postgres
#    password: 123456
#    filters: wall,mergeStat

# Mysql数据库
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/guns?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
#    username: root
#    password: root
#    filters: wall,mergeStat

# Mysql数据库
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.10:3306/qyh-admin?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: zlt2016
    filters: wall,mergeStat

    # 连接池大小根据实际情况调整
    max-active: 20
    max-pool-prepared-statement-per-connection-size: 20

  # redis配置
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    #password:

    lettuce:
      pool:
        # 连接池最大连接数 默认8 ，负数表示没有限制
        max-active: 8
        # 连接池中的最大空闲连接 默认8
        max-idle: 8
        # 连接池中的最小空闲连接 默认0
        min-idle: 0
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
        max-wait: -1
    timeout: 30000

  # 邮件发送配置（改为自己的账号和密码）
  mail:
    host: smtp.369qyhl.com
    port: 25
    username: quanyihui@369qyhl.com
    password: Quanyihulian@666

# 邮件发送（改为自己的账号）
mail:
  from: quanyihui@369qyhl.com
